name: Deploy Heroku

# on:
#   release:
#     types: [published]

on:
  push:
    branches:
      - deployHeroku

jobs:

  deploy-webapp:
    #needs: [unit-test-webapp]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dede-es4c" #Must be unique in Heroku
          heroku_email: "uo277603@uniovi.com"
          usedocker: true
          dontuseforce: true
          appdir: "webapp"
          branch: "deployHeroku"
          docker_build_args: |
            API_URI
            WEBAPP_URI
        env:
          API_URI: http://${{ secrets.DEPLOY_HOST2 }}:5000/api
          WEBAPP_URI: http://${{ secrets.DEPLOY_HOST2 }}:3000

  deploy-restapi:
    #needs: [unit-test-restapi]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dede-es4c" #Must be unique in Heroku
          heroku_email: "uo277603@uniovi.com"
          usedocker: true
          appdir: "restapi"
          branch: "deployHeroku"
          docker_build_args: |
            MONGO_DB_URI
            JWT_SECRET
        env:
          MONGO_DB_URI: mongodb+srv://es4c:es4c@cluster0.hcz1f.mongodb.net/bar_pinchos?retryWrites=true&w=majority
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
